<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-5EVK54D" failures="1" tests="4" name="Test" time="19.474" errors="0" timestamp="2023-10-07T08:23:44 IST">
  <testcase classname="com.spotify.tests.PlayListWithReusableCalls" name="createPlayList" time="17.177"/>
  <testcase classname="com.spotify.tests.PlayListWithReusableCalls" name="getAPlaylist" time="0.782"/>
  <testcase classname="com.spotify.tests.PlayListWithReusableCalls" name="validateUpdatePlaylist" time="0.701">
    <failure type="java.lang.AssertionError" message="expected [201] but found [200]">
      <![CDATA[java.lang.AssertionError: expected [201] but found [200]
at com.spotify.tests.PlayListWithReusableCalls.validateUpdatePlaylist(PlayListWithReusableCalls.java:85)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 38 stack frames]]>
    </failure>
  </testcase> <!-- validateUpdatePlaylist -->
  <testcase classname="com.spotify.tests.PlaylistWithNegativeScenario" name="shouldNotBeAuthorized" time="0.276"/>
</testsuite> <!-- Test -->
